import React,{useEffect,useRef,useState} from 'react';
import {MAX_PACK_BYTES,verifyNaturalPack} from './natural-pack.js';
import {WORDS} from './vocabulary.js';
export default function NaturalVoice({pack,active,onPack,onActive,speaker}){
 const [pending,setPending]=useState(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState('');const controller=useRef(null),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();};},[]);
 async function inspect(file){if(!file)return;const c=new AbortController();controller.current=c;setBusy(true);setError('');setPending(null);setProgress(0);try{if(file.size>MAX_PACK_BYTES)throw new Error('Paket prelazi 20 MiB.');const text=await file.text();if(c.signal.aborted)return;const result=await verifyNaturalPack(JSON.parse(text),{signal:c.signal,onProgress:n=>{if(alive.current)setProgress(n);}});if(alive.current&&!c.signal.aborted)setPending(result);}catch(e){if(alive.current)setError(e instanceof SyntaxError?'Paket nije ispravan JSON.':e.message);}finally{if(alive.current)setBusy(false);if(controller.current===c)controller.current=null;}}
 return <section className="mk-backup"><h3>Bosanski prirodni snimci</h3><p>Originalni glas je eSpeak — robotski. Prirodni paket nije uključen u instalaciju. Uvezi lokalni paket 95 snimaka s nazivom i licencom. Nema slanja serveru ni automatskog govora.</p><label htmlFor="mk-bs-pack">Lokalni BS paket (.json, do 20 MiB)</label><input id="mk-bs-pack" type="file" accept="application/json,.json" disabled={busy} onChange={e=>{inspect(e.target.files?.[0]);e.target.value='';}}/>{busy&&<div role="status">Provjera snimaka {progress}/95 <button className="mk-button" onClick={()=>controller.current?.abort()}>Prekini uvoz paketa</button></div>}{error&&<p className="mk-error" role="alert">{error}</p>}{pending&&<div className="mk-banner"><strong>{pending.name} · 95 snimaka</strong><p>Prijavljeni izvor: {pending.source}. Licenca: {pending.license}. Tehnička provjera ne potvrđuje izgovor — prvo preslušaj.</p><div className="mk-sheet-actions"><button className="mk-button" onClick={()=>speaker.speak([{...WORDS[0],audio:pending.words.find(w=>w.id===WORDS[0].id).audio,audioSource:pending.name}],'bs')}>Preslušaj JA</button><button className="mk-button primary" onClick={()=>{speaker.stop(false);onPack(pending);onActive(true);setPending(null);}}>Koristi paket u ovoj sesiji</button><button className="mk-button" onClick={()=>setPending(null)}>Odustani</button></div></div>}{pack&&<><p><strong>{pack.name}</strong> · {active?'Aktivan':'Nije aktivan'}</p><button className="mk-button" onClick={()=>{speaker.stop(false);onActive(!active);}}>{active?'Koristi originalni eSpeak':'Koristi lokalni paket'}</button></>}<p><small>Paket ostaje samo u memoriji ove sesije. Poslije ponovnog otvaranja uvezi svoj fajl ponovo; nije dio backupa table i ne zauzima prostor tvojih sačuvanih simbola. Vlastiti simboli zadržavaju svoje snimke.</small></p></section>;
}
