import React,{useEffect,useRef,useState} from 'react';
import { X,Download,Plus,Lock,Play } from '@openai/apps-sdk-ui/components/Icon';
import { CATEGORIES,COLORS,stateBytes,validateState } from './domain.js';
import { exportBackupText,parseBackupText,copyBackupText,selectBackupText } from './backup-transfer.js';
import VoiceSetup from './VoiceSetup.jsx';
import NaturalVoice from './NaturalVoice.jsx';
import VoiceRecorder from './VoiceRecorder.jsx';
import { prepareImage,prepareAudio,verifyBackupMedia } from './media.js';
const blankSymbol=()=>({id:'user_'+crypto.randomUUID(),label:'',spoken:'',category:'custom',color:COLORS.custom,image:'',audio:''});
export default function Settings({state,save,previous,speaker,caps,voiceSetup,voiceState,speechStatus,naturalPack,naturalActive,onPack,onNaturalActive,close,onImport,canSave}) {
 const [unlockText,setUnlockText]=useState(''),[unlocked,setUnlocked]=useState(false),[editor,setEditor]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState(null),[removeConfirm,setRemoveConfirm]=useState(false);
 const [exportText,setExportText]=useState(''),[pasteText,setPasteText]=useState(''),[copying,setCopying]=useState(false);
 const [recording,setRecording]=useState(false);
 const exportField=useRef(null);
 const dialog=useRef(null);const alive=useRef(true);
 useEffect(()=>{const previousFocus=document.activeElement;dialog.current.querySelector('button')?.focus();alive.current=true;voiceSetup.refresh();return()=>{alive.current=false;speaker.stop(false);previousFocus?.focus();};},[]);
 function keyboard(e){if(e.key==='Escape'&&!busy){speaker.stop(false);close();}if(e.key==='Tab'){const items=[...dialog.current.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')].filter(el=>el.offsetParent!==null);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}
 async function run(operation){setError('');setNotice('');setBusy(true);try{await operation();}catch(e){if(alive.current)setError(e.message||'Operacija nije uspjela.');}finally{if(alive.current)setBusy(false);}}
 async function reviewImportText(text){const next=await verifyBackupMedia(parseBackupText(text));setPending(next);setNotice('Backup je validiran. Pregledajte zamjenu prije potvrde.');}
 async function importFile(file){if(!file)return;await run(async()=>{if(file.size>650000)throw new Error('Backup je prevelik (najviše 650 kB).');await reviewImportText(await file.text());});}
 function showExport(){try{setError('');setExportText(exportBackupText(state));setNotice('Lokalni backup JSON je spreman. Kopiraj ga i sačuvaj kao .json datoteku na svom uređaju.');}catch(e){setError(e.message);}}
 async function copyExport(){setCopying(true);setError('');const outcome=await copyBackupText(exportText,window.mobius?.clipboard,exportField.current);if(!alive.current)return;setCopying(false);setNotice(outcome==='copied'?'JSON je kopiran. Sačuvaj ga kao .json datoteku; kopiranje još nije sačuvan backup fajl.':outcome==='selected'?'Automatsko kopiranje nije uspjelo. Tekst je odabran: koristi Ctrl/Cmd+C ili dodirni i drži pa Kopiraj.':'Automatsko kopiranje nije uspjelo. Ručno odaberi i kopiraj vidljivi JSON.');}
 async function replace(next){await run(async()=>{const ok=await save(next,{preserve:true,transactional:true});if(!ok)throw new Error('Zamjena nije sačuvana; prethodna tabla ostaje aktivna.');onImport(next);setPending(null);setEditor(null);setNotice('Tabla je zamijenjena. Prethodna verzija je sačuvana lokalno za povrat.');});}
 async function saveSymbol(e){e.preventDefault();await run(async()=>{const custom=state.custom.filter(w=>w.id!==editor.id);const found=state.custom.findIndex(w=>w.id===editor.id);if(found>=0)custom.splice(found,0,editor);else custom.push(editor);const next=validateState({...state,custom});if(!await save(next,{transactional:true}))throw new Error('Simbol nije sačuvan. Provjerite lokalno čuvanje.');window.mobius?.signal('item_created',{type:'symbol'});setEditor(null);setNotice('Vlastiti simbol je sačuvan samo na ovom uređaju.');});}
 function setField(key,value){setEditor(old=>({...old,[key]:value}));}
 const isExisting=editor&&state.custom.some(w=>w.id===editor.id);
 return <div className="mk-scrim" role="dialog" aria-modal="true" aria-label="Postavke MAAK" onKeyDown={keyboard}><div className="mk-sheet" ref={dialog}>
  <div className="mk-sheet-header"><h2>Postavke</h2><button className="mk-button" aria-label="Zatvori postavke" disabled={busy} onClick={()=>{speaker.stop(false);close();}}><X/></button></div>
  <p>Prilagodi tablu sebi. Originalni simboli uvijek ostaju sačuvani.</p>
  <h3>Veličina simbola</h3><div className="mk-seg" aria-label="Veličina simbola">{[['compact','Manji'],['standard','Srednji'],['large','Veći']].map(([size,label])=><button key={size} aria-pressed={state.size===size} disabled={busy} onClick={()=>save({...state,size})}>{label}</button>)}</div>
  <h3>Glas</h3><div className="mk-banner" role="status">{speechStatus}<div className="mk-sheet-actions"><button className="mk-button danger" onClick={()=>speaker.stop()}>Prekini zvuk</button></div></div><p><strong>Bosanski:</strong> originalni sintetički snimci riječi. Za vlastiti simbol dodaj odgovarajući audio.</p>
  <VoiceSetup setup={voiceSetup} value={voiceState} speaker={speaker}/>
  <h3>Moji podaci</h3><p>Čuvaju se samo u ovom pregledniku. Redovno izvezi backup prije brisanja podataka preglednika ili promjene uređaja. Datoteka uključuje tvoje slike i audio — čuvaj je privatno.</p><p>{state.custom.length} / 50 vlastitih simbola · {Math.ceil(stateBytes(state)/1024)} / 440 KiB</p>
  <div className="mk-sheet-actions"><button className="mk-button" disabled={busy} onClick={showExport}><Download/>Izvezi backup</button></div>
  {exportText&&<section className="mk-backup"><h3>Lokalni backup JSON</h3><p>Ovaj okvir ne preuzima fajlove direktno. JSON ostaje ovdje: kopiraj ga u lokalni tekst editor i sačuvaj kao <strong>MAAK-backup.json</strong>. Sadrži lične medije — ne šalji ga u chat ili javne servise.</p><label htmlFor="mk-export-json">Cijeli backup JSON</label><textarea id="mk-export-json" className="mk-backup-text" ref={exportField} value={exportText} readOnly spellCheck={false} wrap="off"/><div className="mk-sheet-actions"><button className="mk-button primary" disabled={copying} onClick={copyExport}>{copying?'Kopiranje…':'Kopiraj JSON'}</button><button className="mk-button" onClick={()=>{const selected=selectBackupText(exportField.current);setNotice(selected?'Tekst je odabran. Koristi Ctrl/Cmd+C ili dodirni i drži pa Kopiraj.':'Ručno odaberi i kopiraj vidljivi JSON.');}}>Odaberi sav tekst</button><button className="mk-button" disabled={copying} onClick={()=>setExportText('')}>Sakrij JSON</button></div></section>}
  <h3><Lock/> Zaštićeno uređivanje</h3><p>Štiti od slučajnih promjena, nije lozinka. Za uređivanje i uvoz upiši MAAK; za komunikaciju nije potrebno.</p>
  {!canSave&&<div className="mk-error">Lokalno čuvanje nije dostupno. Uređivanje je zaključano; postojeći podaci se ne zamjenjuju.</div>}
  {!unlocked?<><label htmlFor="mk-unlock">Upišite MAAK za uređivanje</label><input id="mk-unlock" autoComplete="off" value={unlockText} onChange={e=>setUnlockText(e.target.value)}/><div className="mk-sheet-actions"><button className="mk-button primary" disabled={unlockText!=='MAAK'||!canSave} onClick={()=>{setUnlocked(true);setUnlockText('');}}>Otključaj uređivanje</button></div></>:<>
   <div className="mk-sheet-actions"><button className="mk-button" disabled={busy} onClick={()=>{setEditor(null);setPending(null);setPasteText('');setUnlocked(false);}}>Zaključaj</button><button className="mk-button primary" disabled={busy} onClick={()=>{setEditor(blankSymbol());setRemoveConfirm(false);}}><Plus/>Novi simbol</button></div>
   <label htmlFor="mk-import">Uvezi MAAK Möbius backup (JSON)</label><input id="mk-import" type="file" accept="application/json,.json" disabled={busy} onChange={e=>{importFile(e.target.files?.[0]);e.target.value='';}}/>
   <label htmlFor="mk-import-json">Ili zalijepi backup JSON lokalno</label><textarea id="mk-import-json" className="mk-backup-text" maxLength={650000} disabled={busy} value={pasteText} onChange={e=>{setPasteText(e.target.value);setPending(null);}} spellCheck={false} placeholder="Zalijepi MAAK backup…"/><div className="mk-sheet-actions"><button className="mk-button" disabled={busy||!pasteText.trim()} onClick={()=>run(()=>reviewImportText(pasteText))}>Provjeri zalijepljeni JSON</button></div>
   {previous&&<div className="mk-sheet-actions"><button className="mk-button" disabled={busy} onClick={()=>{setPending(previous);setNotice('Pregled prethodne table; ništa još nije zamijenjeno.');}}>Vrati prethodnu tablu…</button></div>}
   {pending&&<div className="mk-banner"><strong>Pregled zamjene</strong><p>{pending.custom.length} vlastitih simbola · {pending.sentence.length} riječi u traci · {pending.mode==='bs'?'Bosanski':'English demo'} · {pending.size}. Sada: {state.custom.length} vlastitih simbola. Nova tabla zamjenjuje trenutnu; prethodna se automatski čuva za povrat.</p><div className="mk-sheet-actions"><button className="mk-button" disabled={busy} onClick={()=>setPending(null)}>Odustani</button><button className="mk-button primary" disabled={busy} onClick={()=>replace(pending)}>Sačuvaj prethodnu i zamijeni</button></div></div>}
   <NaturalVoice pack={naturalPack} active={naturalActive} onPack={onPack} onActive={onNaturalActive} speaker={speaker}/>
   <h3>Vlastiti simboli</h3><div className="mk-settings-list">{state.custom.map(w=><button className="mk-button" disabled={busy} key={w.id} onClick={()=>{setEditor({...w});setRemoveConfirm(false);}}>Uredi {w.label}</button>)}</div>{!state.custom.length&&<p>Još nema vlastitih simbola. Dodaj poznati predmet, osobu ili mjesto.</p>}
   {editor&&<form onSubmit={saveSymbol}><h3>{isExisting?'Uredi vlastiti simbol':'Novi vlastiti simbol'}</h3><label htmlFor="mk-label">Naziv na tabli</label><input id="mk-label" required maxLength={40} value={editor.label} onChange={e=>setField('label',e.target.value)}/><label htmlFor="mk-spoken">Tekst izgovora / sadržaj snimka</label><input id="mk-spoken" required maxLength={120} value={editor.spoken} onChange={e=>setField('spoken',e.target.value)}/><p>Dodaj snimak koji izgovara ovaj tekst. Bez snimka simbol može biti na tabli, ali ne može govoriti.</p>
    <div className="mk-form-cols"><div><label htmlFor="mk-cat">Kategorija</label><select id="mk-cat" value={editor.category} onChange={e=>setField('category',e.target.value)}>{Object.entries(CATEGORIES).filter(([k])=>!['core','all'].includes(k)).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></div><div><label htmlFor="mk-color">Boja</label><input id="mk-color" type="color" value={editor.color} onChange={e=>setField('color',e.target.value)}/></div></div>
    <label htmlFor="mk-image">Lična slika · ostaje na uređaju</label><input id="mk-image" type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)run(async()=>setField('image',await prepareImage(file)));e.target.value='';}}/>{editor.image&&<><img className="mk-editor-preview" src={editor.image} alt="Pregled lične slike"/><button type="button" className="mk-button" onClick={()=>setField('image','')}>Ukloni sliku iz nacrta</button></>}
    <VoiceRecorder key={editor.id} caps={caps} disabled={busy} onBusyChange={setRecording} onAudio={data=>setField('audio',data)}/>
    <label htmlFor="mk-audio">Lokalni audio · do 8 sekundi / 130 kB</label><input id="mk-audio" type="file" accept="audio/wav,audio/x-wav,audio/mpeg,audio/ogg,audio/webm" disabled={busy||recording} onChange={e=>{const file=e.target.files?.[0];if(file)run(async()=>setField('audio',await prepareAudio(file)));e.target.value='';}}/>{editor.audio&&<div className="mk-sheet-actions"><button type="button" className="mk-button" onClick={()=>speaker.speak([editor],'bs')}>Preslušaj snimak</button><button type="button" className="mk-button" onClick={()=>{speaker.stop();setField('audio','');}}>Ukloni audio iz nacrta</button></div>}
    <div className="mk-sheet-actions"><button type="button" className="mk-button" disabled={busy} onClick={()=>{speaker.stop(false);setEditor(null);}}>Odustani</button><button type="submit" className="mk-button primary" disabled={busy||recording}>Sačuvaj simbol</button></div>
    {isExisting&&<div className="mk-sheet-actions"><button type="button" className="mk-button danger" disabled={busy} onClick={()=>setRemoveConfirm(true)}>Ukloni vlastiti simbol…</button></div>}{removeConfirm&&<div className="mk-error">Ukloniti {editor.label}? Prethodna tabla će ostati dostupna za povrat.<div className="mk-sheet-actions"><button type="button" className="mk-button" onClick={()=>setRemoveConfirm(false)}>Zadrži</button><button type="button" className="mk-button danger" disabled={busy} onClick={()=>replace({...state,custom:state.custom.filter(w=>w.id!==editor.id),sentence:state.sentence.filter(id=>id!==editor.id),alternateSentence:(state.alternateSentence||[]).filter(id=>id!==editor.id)})}>Potvrdi uklanjanje</button></div></div>}
   </form>}
  </>}
  {busy&&<p role="status">Provjera i čuvanje…</p>}{error&&<p className="mk-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
  <div className="mk-footer">MAAK · Eldar Ćerim / PONTEM. Nije medicinski validiran proizvod. Licence i tehnički detalji su u dokumentaciji edicije.</div>
 </div></div>;
}
