import test from 'node:test';import assert from 'node:assert/strict';import {createSpeaker} from '../speech.js';
class MockContext {state='running';destination={};get currentTime(){return performance.now()/1000;}resume(){return Promise.resolve();}createBuffer(_c,n,rate){return {duration:n/rate,copyToChannel(){}};}createBufferSource(){return {connect(){},disconnect(){},start(){},stop(){}};}close(){return Promise.resolve();}}
global.window={AudioContext:MockContext};
test('missing real Voice model gives setup, never synthetic success',async()=>{const states=[];let opens=0;const caps={available:()=>true,invoke:async()=>({activeModel:null}),open:()=>{opens++;}};const s=createSpeaker(caps,x=>x,x=>states.push(x));await s.speak([{spoken:'hello'}],'en');assert.equal(opens,0);assert.ok(states.at(-1).includes('Voice nije spreman'));assert.ok(!states.some(s=>s.includes('završena')));s.dispose();});
test('wrong selected Voice language never receives English or Bosnian text',async()=>{let opened=false;const states=[];const s=createSpeaker({available:()=>true,invoke:async()=>({activeModel:{name:'Lola',language:'Spanish'}}),open:()=>{opened=true;}},x=>x,x=>states.push(x));await s.speak([{spoken:'hello'}],'en');assert.equal(opened,false);assert.match(states.at(-1),/ne English/);s.dispose();});
test('custom Bosnian text without its own audio is not falsely synthesized',async()=>{let invoked=false;const states=[];const s=createSpeaker({invoke:()=>{invoked=true;}},x=>x,x=>states.push(x));await s.speak([{spoken:'lična riječ'}],'bs');assert.equal(invoked,false);assert.match(states.at(-1),/nema audio snimak/);s.dispose();});
test('streamed audio invokes real contract shape, pins model and ends only after queued samples',async()=>{const callbacks={};let request;const statuses=[];const session={on(k,f){callbacks[k]=f;return()=>{delete callbacks[k];};},get result(){return Promise.resolve().then(()=>{callbacks.audio({samples:new Float32Array(240).fill(.1)});callbacks.boundary({pauseAfterMs:0});});},cancel(){}};
const caps={available:()=>true,invoke:async()=>({activeModel:{id:'pocket-tts-alba',name:'Alba',language:'English',sampleRate:24000}}),open(name,input){request={name,input};return session;}};const s=createSpeaker(caps,x=>x,x=>statuses.push(x));await s.speak([{spoken:'I'},{spoken:'want water'}],'en');assert.equal(request.name,'media.speech');assert.equal(request.input.modelId,'pocket-tts-alba');assert.equal(request.input.document.locale,'en-GB');assert.equal(request.input.document.segments[0].text,'I want water');assert.match(statuses.at(-1),/završena/);s.dispose();});
test('stop before asynchronous catalog readiness prevents late synthesis and false completion',async()=>{let resolve,opened=false;const statuses=[];const s=createSpeaker({available:()=>true,invoke:()=>new Promise(r=>resolve=r),open(){opened=true;}},x=>x,x=>statuses.push(x));const p=s.speak([{spoken:'hello'}],'en');while(!resolve)await new Promise(r=>setTimeout(r,0));s.stop();resolve({activeModel:{id:'a',language:'English'}});await p;assert.equal(opened,false);assert.equal(statuses.at(-1),'Prekinuto.');s.dispose();});
test('audio scheduling failure is never reported as successful speech',async()=>{const old=window.AudioContext;window.AudioContext=class extends MockContext{createBuffer(){throw new Error('no audio');}};const callbacks={},statuses=[];const caps={available:()=>true,invoke:async()=>({activeModel:{id:'a',name:'Alba',language:'English',sampleRate:24000}}),open(){return {on(k,f){callbacks[k]=f;return()=>{};},get result(){return Promise.resolve().then(()=>callbacks.audio({samples:new Float32Array(100)}));},cancel(){}};}};const s=createSpeaker(caps,x=>x,x=>statuses.push(x));await s.speak([{spoken:'hello'}],'en');assert.match(statuses.at(-1),/nije mogao/);assert.ok(!statuses.some(x=>x.includes('završena')));s.dispose();window.AudioContext=old;});
test('all-zero Voice packets never imply successful playback',async()=>{const states=[],callbacks={};const caps={available:()=>true,invoke:async()=>({activeModel:{id:'a',name:'Alba',language:'English',sampleRate:24000}}),open(){return {on(k,f){callbacks[k]=f;return()=>{};},get result(){return Promise.resolve().then(()=>callbacks.audio({samples:new Float32Array(240)}));},cancel(){}};}};const s=createSpeaker(caps,x=>x,x=>states.push(x));await s.speak([{spoken:'I want water'}],'en');assert.match(states.at(-1),/nije vratio čujne/);assert.ok(!states.some(x=>x.includes('završena')));s.dispose();});
test('never-settled audio unlock fails visibly and never starts a Voice session',async()=>{const old=window.AudioContext;window.AudioContext=class extends MockContext{resume(){return new Promise(()=>{});}};let invoked=false;const states=[];const s=createSpeaker({invoke(){invoked=true;}},x=>x,x=>states.push(x),{unlockMs:10});await s.speak([{spoken:'hello'}],'en');assert.equal(invoked,false);assert.match(states.at(-1),/otključao/);s.dispose();window.AudioContext=old;});
test('English synthesis stall is bounded and canceled without manufactured success',async()=>{let canceled=0;const states=[];const caps={available:()=>true,invoke:async()=>({activeModel:{id:'a',name:'Alba',language:'English',sampleRate:24000}}),open(){let reject;return {on(){return()=>{};},result:new Promise((_r,j)=>reject=j),cancel(){canceled++;reject(new Error('cancelled'));}};}};const s=createSpeaker(caps,x=>x,x=>states.push(x),{idleMs:10});await s.speak([{spoken:'hello'}],'en');assert.ok(canceled);assert.ok(!states.some(x=>x.includes('završena')));s.dispose();});
test('user gesture resumes audio before catalog or synthesis request',async()=>{const old=window.AudioContext,calls=[];window.AudioContext=class extends MockContext{resume(){calls.push('resume');return Promise.resolve();}};const s=createSpeaker({available:()=>true,invoke:async()=>{calls.push('catalog');return {activeModel:null};}},x=>x,()=>{});const p=s.speak([{spoken:'hello'}],'en');assert.deepEqual(calls,['resume']);await p;assert.deepEqual(calls,['resume','catalog']);s.dispose();window.AudioContext=old;});
test('personal Bosnian audio decodes locally without fetch and uses its original sample rate',async()=>{const old=window.AudioContext;const oldFetch=global.fetch;let fetched=false;global.fetch=()=>{fetched=true;throw new Error('network forbidden');};window.AudioContext=class extends MockContext{decodeAudioData(){return Promise.resolve({sampleRate:16000,getChannelData:()=>new Float32Array(160).fill(.1)});}};const states=[];const s=createSpeaker({},x=>x,x=>states.push(x));await s.speak([{audio:'data:audio/wav;base64,AAAA',spoken:'voda'}],'bs');assert.equal(fetched,false);assert.match(states.at(-1),/završena/);s.dispose();window.AudioContext=old;global.fetch=oldFetch;});
test('stop during a live English stream cancels session and rejects late playback/completion',async()=>{let audio,resolve,cancel=0;const states=[];const caps={available:()=>true,invoke:async()=>({activeModel:{id:'a',name:'Alba',language:'English',sampleRate:24000}}),open(){return {on(k,f){if(k==='audio')audio=f;return()=>{};},result:new Promise(r=>resolve=r),cancel(){cancel++;resolve();}};}};const s=createSpeaker(caps,x=>x,x=>states.push(x));const p=s.speak([{spoken:'I want water'}],'en');while(!audio)await new Promise(r=>setTimeout(r,0));s.stop();audio({samples:new Float32Array(240).fill(.1)});await p;assert.ok(cancel);assert.equal(states.at(-1),'Prekinuto.');s.dispose();});
