import test from 'node:test';import assert from 'node:assert/strict';import {createVoiceSetup,englishPlan,voiceFailure} from '../voice-setup.js';
const catalog=()=>({engines:[{id:'e',languages:['English'],state:'missing',storedBytes:100,cachedBytes:0}],models:[{id:'a',voice:'Alba',language:'English',profileState:'missing',profileBytes:10}]});
function host({failOnce=false,stalled=false}={}){let ready=false,engine=false,profile=false,attempts=0;const calls=[];let progress;let reject;
return {calls,get progress(){return progress;},caps:{available:()=>true,async invoke(name,input){calls.push([name,input.operation]);if(name==='media.speech')return {activeModel:ready?{id:'a',name:'Alba',language:'English'}:null};if(input.operation==='select'){assert.ok(engine&&profile);ready=true;return {};}const c=catalog();if(engine)c.engines[0].state='ready';if(profile)c.models[0].profileState='ready';return c;},open(name,input){calls.push([name,input.operation]);let resolve;const result=new Promise((a,b)=>{resolve=a;reject=b;});const s={on(_e,f){progress=f;return()=>{};},result,cancel(){reject(new Error('cancelled'));}};queueMicrotask(()=>{if(stalled)return;if(failOnce&&attempts++===0){reject(new Error('network unavailable'));return;}if(input.operation==='install-engine')engine=true;else profile=true;progress?.({downloadedBytes:10,totalBytes:10});resolve({});});return s;}}};}
test('catalog is read-only and fresh-device setup requires an explicit prepare, then verifies selected playback',async()=>{const h=host(),values=[];const setup=createVoiceSetup(h.caps,v=>values.push(v));await setup.refresh();assert.ok(!h.calls.some(x=>x[1].startsWith('install')));assert.equal(setup.state.ready,false);await setup.prepare();assert.equal(setup.state.ready,true);assert.deepEqual(h.calls.filter(x=>/install|select/.test(x[1])).map(x=>x[1]),['install-engine','install-profile','select']);assert.match(setup.state.message,/Izgovori/);setup.dispose();});
test('network error is visible and explicit retry resumes without claiming ready before verification',async()=>{const h=host({failOnce:true}),setup=createVoiceSetup(h.caps,()=>{});await setup.prepare();assert.equal(setup.state.ready,false);assert.match(setup.state.error,/network/);await setup.prepare();assert.equal(setup.state.ready,true);setup.dispose();});
test('cancel during download settles setup and ignores late progress',async()=>{const h=host({stalled:true}),setup=createVoiceSetup(h.caps,()=>{});const p=setup.prepare();while(!h.progress)await new Promise(r=>setTimeout(r,0));setup.cancel();h.progress({downloadedBytes:20,totalBytes:100});await p;assert.equal(setup.state.ready,false);assert.equal(setup.state.busy,false);assert.match(setup.state.message,/prekinuta/);setup.dispose();});
test('stalled transfer is bounded and never selects incomplete model',async()=>{const h=host({stalled:true}),setup=createVoiceSetup(h.caps,()=>{},{idleMs:10});await setup.prepare();assert.equal(setup.state.ready,false);assert.ok(setup.state.error);assert.ok(!h.calls.some(x=>x[1]==='select'));setup.dispose();});
test('missing English contract is actionable, no guessed language or download',async()=>{assert.throws(()=>englishPlan({engines:[],models:[]}),/nema podržani/);});
test('ready English voice is preserved; prepare never silently replaces a clone or changes selection',async()=>{const calls=[];const caps={available:()=>true,invoke:async(name,input)=>{calls.push(input.operation);return name==='media.speech'?{activeModel:{id:'clone',name:'My English',language:'English'}}:catalog();},open(){throw new Error('must not download');}};const setup=createVoiceSetup(caps,()=>{});await setup.prepare();assert.equal(setup.state.active.id,'clone');assert.ok(!calls.includes('select'));setup.dispose();});

test('real asset HTTP502 is translated into a concrete source blocker, not readiness or an unofficial TTS fallback',()=>{const text=voiceFailure({code:'download_failed',message:'The device asset source returned 502.'});assert.match(text,/HTTP 502/);assert.match(text,/Otvori Voice/);assert.match(text,/Ne briši/);assert.ok(!text.includes('The device'));});

test('HTTP502 retries same verified package exactly once, then exposes Voice recovery without looping or selecting',async()=>{let opens=0;const caps={available:()=>true,invoke:async(name)=>name==='media.speech'?{activeModel:null}:catalog(),open(){opens++;return {on(){return()=>{};},result:Promise.reject(Object.assign(new Error('The device asset source returned 502.'),{code:'download_failed'})),cancel(){}};}};const setup=createVoiceSetup(caps,()=>{});await setup.prepare();assert.equal(opens,2);assert.equal(setup.state.ready,false);assert.match(setup.state.error,/Otvori Voice/);setup.dispose();});
